try:
    10 / 0

except Exception as e:
    # except ZeroDivisionError as e:
    # except ZeroDivisionError:
    print(f"Ocurrió un error: {e}")
    # print(f'Ocurrió un error: División debe ser cero')
